name: untitled2
description: A new Flutter project.
publish_to: 'none'

version: 1.7.6+52

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  permission_handler: ^11.3.1
  flutter_svg: ^2.1.0
  http: ^1.4.0
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.5.3
  extended_nested_scroll_view: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_widget_from_html: ^0.16.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  # firebase_core_platform_interface: ^5.0.0

  # loading_skeleton_niu: ^0.0.1  # Replaced with shimmer
  # http_auth: ^1.0.4  # Not used
  # firebase_core: ^3.3.0
  # firebase_messaging: ^15.0.4  

  persistent_bottom_nav_bar:
    git:
      url: https://github.com/HamzaSamirAmmar/PersistentBottomNavBar.git
  # stripe_sdk:  # Remove if not used
  #   git: https://github.com/cmtboy/stripe-sdk

  url_launcher: ^6.3.1
  percent_indicator: ^4.2.3
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.1
  # razorpay_flutter: ^1.4.0  # Remove if not used

  open_document: ^1.0.7
  # paytm_allinonesdk:
  #   git: https://github.com/cmtboy/paytm_allinonesdk-1.2.6

  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.3.0
  connection_notifier: ^2.0.1
  # flutter_inappwebview: ^6.1.5
  # sn_progress_dialog: ^1.1.4  # Replace with built-in dialog

  vdocipher_flutter: ^2.6.6

  # flutter_paystack:
  #   git:
  #     url: https://github.com/I-driod/flutter_paystack.git
  #     ref: master

  # eko_jitsi:
  #   path: eko-jitsi

  fancy_shimmer_image:
    path: fancy-shimmer-image
  flutter_blurhash: ^0.8.2
  purchases_flutter: ^9.1.0
  # youtube_player_flutter: ^9.0.1
  youtube_explode_dart: ^2.1.0
  flutter_slidable: ^4.0.0
  # share_plus: ^7.2.2

  google_fonts: ^6.2.1
  awesome_notifications: ^0.10.1
  file_picker: ^9.0.0
  reactive_forms: ^17.0.1
  open_file: ^3.3.2
  chewie: ^1.8.3
  video_player: ^2.10.0
  # pdfrx: ^1.1.34
  device_info_plus: ^10.1.2
  sqflite: ^2.4.2
  path_provider: ^2.1.4
  carousel_slider: ^5.1.1

dependency_overrides:
  win32: ^5.5.4
  http: ^0.13.5
  archive: ^3.6.1

  webview_flutter: ^4.8.0
  webview_flutter_android: 4.7.0

  intl: ^0.17.0
  
  # Fix flutter_widget_from_html compatibility
  flutter_widget_from_html: ^0.16.0
  flutter_widget_from_html_core: ^0.16.0
  
  # Fix flutter_slidable compatibility
  flutter_slidable: ^4.0.0
  
  # Fix pdfrx compatibility
  # pdfrx: ^1.1.34
  
  # Fix fluttertoast compatibility
  fluttertoast: ^8.2.12
  
  # Fix sqflite compatibility
  sqflite: ^2.4.2
  
  # Fix url_launcher_android compatibility
  url_launcher_android: ^6.3.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo-app.png"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
    - lib/language/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf